# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 01:52
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardensapp', '0002_auto_20160801_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='waypoints',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=3857),
        ),
    ]
