# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 01:53
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardensapp', '0003_auto_20160801_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='waypoints',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=4326),
        ),
    ]
